language: python
python:
  - "3.8"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - pytest lib --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
